micronaut:
    application:
        name: micronaut-demo
datasources:
    default:
        url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:postgres}
        username: postgres
        password: ""
        driverClassName: org.postgresql.Driver