micronaut:
    application:
        name: micronaut-demo
postgres:
    reactive:
        client:
            port: 5432
            host: localhost
            database: postgres
            user: postgres
            maxSize: 5

