version: "3"
services:
  app:
    build: .
    image: quarkus-demo
    environment:
      - QUARKUS_DATASOURCE_URL=jdbc:postgresql://db/postgres
    depends_on:
      - db
    ports:
      - 8080:8080
  db:
    image: postgres:11.2
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432